[phases.setup]
nixPkgs = ["python39", "gcc"]

[phases.install]
commands = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
command = "gunicorn project_pfa.project_pfa.wsgi:application --bind 0.0.0.0:$PORT"