# Generated by Django 4.2.20 on 2025-04-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HubArtistique", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="firstName",
        ),
        migrations.RemoveField(
            model_name="user",
            name="lastName",
        ),
    ]
