# Generated by Django 4.2.20 on 2025-04-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HubArtistique", "0003_remove_user_firstname_remove_user_lastname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="", max_length=150),
        ),
    ]
