# Generated by Django 4.2.20 on 2025-04-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HubArtistique", "0005_remove_room_photo_url_room_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="logo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
