# Generated by Django 4.2.20 on 2025-05-03 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("HubArtistique", "0006_equipment_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="reservation",
            name="attendees",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="reservation",
            name="purpose",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="selected_equipment",
            field=models.ManyToManyField(
                blank=True, related_name="reservations", to="HubArtistique.equipment"
            ),
        ),
        migrations.AddField(
            model_name="reservationhistory",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservationhistory",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="HubArtistique.room",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservationhistory",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="HubArtistique.reservation",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="HubArtistique.building",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="is_active",
            field=models.IntegerField(
                choices=[(1, "Active"), (2, "Maintenance"), (3, "Inactive")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="roomequipment",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_equipment",
                to="HubArtistique.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="roomequipment",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_equipment",
                to="HubArtistique.room",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roomequipment",
            unique_together={("room", "equipment")},
        ),
    ]
