# Generated by Django 4.2.20 on 2025-05-04 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("HubArtistique", "0007_equipment_hourly_rate_reservation_attendees_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="roomequipment",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="hourly_rate",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="attendees",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="purpose",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="selected_equipment",
        ),
        migrations.RemoveField(
            model_name="reservationhistory",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="reservationhistory",
            name="updated_by",
        ),
        migrations.AlterField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="HubArtistique.room"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="reservationhistory",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="HubArtistique.reservation",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="HubArtistique.building"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="roomequipment",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="HubArtistique.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="roomequipment",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="HubArtistique.room"
            ),
        ),
    ]
