# Generated by Django 4.2.20 on 2025-05-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HubArtistique", "0008_alter_roomequipment_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="is_active",
        ),
        migrations.AddField(
            model_name="reservation",
            name="number_of_attendees",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="room",
            name="additional_equipment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="disponibility",
            field=models.CharField(
                choices=[
                    ("dispo", "Available"),
                    ("maintenance", "Maintenance"),
                    ("no", "Unavailable"),
                ],
                default="dispo",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="roomequipment",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
