# Generated by Django 4.2.20 on 2025-05-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HubArtistique", "0009_remove_room_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="features",
            field=models.ManyToManyField(blank=True, to="HubArtistique.feature"),
        ),
    ]
