# Generated by Django 4.2.20 on 2025-05-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HubArtistique", "0010_feature_room_features"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="additional_equipment",
        ),
        migrations.RemoveField(
            model_name="room",
            name="available_equipment",
        ),
        migrations.AddField(
            model_name="room",
            name="additional_equipment",
            field=models.ManyToManyField(
                blank=True,
                related_name="rooms_with_additional_equipment",
                to="HubArtistique.equipment",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="available_equipment",
            field=models.ManyToManyField(
                blank=True,
                related_name="rooms_with_available_equipment",
                to="HubArtistique.equipment",
            ),
        ),
    ]
