# Generated by Django 4.2.20 on 2025-05-12 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HubArtistique', '0012_reservationhistory_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('attendees', models.CharField(default='', max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipment_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HubArtistique.cart')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HubArtistique.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='HubArtistique.equipment'),
        ),
        migrations.CreateModel(
            name='CartItemEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HubArtistique.cartitem')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HubArtistique.equipment')),
            ],
            options={
                'unique_together': {('cart_item', 'equipment')},
            },
        ),
    ]
